name: Example Workflow

on: [push]

jobs:
  print_secret_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret value
        run: echo "Secret value is ${{ secrets.GIST_DATABASE }}"
        env:
          GIST_DATABASE: ${{ secrets.GIST_DB_TOKEN }}
